feat(NIST 800-53): add DMS rule to pack
cdklabs/cdk-nag pull request #106
Opened 2021-08-04 19:38 UTC by jen-rich

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-04 21:34 UTC, dontirun requested changes
Additionally run the `npx projen build`or `npx projen eslint` command locally so that the build does not fail on linting

2021-08-04 21:34 UTC, dontirun commented on RULES.md
> +| [NIST.800.53-DynamoDBPITREnabled](https://docs.aws.amazon.com/config/latest/developerguide/dynamodb-pitr-enabled.html)                                       | 'The DynamoDB table does not have Poin
```suggestion
| [NIST.800.53-DynamoDBPITREnabled](https://docs.aws.amazon.com/config/latest/developerguide/dynamodb-pitr-enabled.html)                                       | The DynamoDB table does not have Point-in-time Recovery enabled - (Control IDs: CP-9(b), CP-10, SI-12).                                        | The recovery maintains continuous backups of your table for the last 35 days.                                                                                                                                                                                                                                                                                 |
```

2021-08-04 21:34 UTC, dontirun commented on RULES.md
> +| [NIST.800.53-DMSReplicationNotPublic](https://docs.aws.amazon.com/config/latest/developerguide/dms-replication-not-public.html)                                       | 'DMS replication is public -
```suggestion
| [NIST.800.53-DMSReplicationNotPublic](https://docs.aws.amazon.com/config/latest/developerguide/dms-replication-not-public.html)                                       | The DMS replication instance is public - (Control ID: AC-4).                                        | DMS replication instances can contain sensitive information and access control is required for such accounts.                                                                                                                                                                                                                                                                                 |
```

2021-08-04 21:34 UTC, dontirun commented on src/NIST-800-53/nist-800-53.ts
> +        'The DMS replication is public (Control IDs: AC-3).';
```suggestion
        'The DMS replication instance is public (Control IDs: AC-3).';
```

2021-08-04 21:34 UTC, dontirun commented on src/NIST-800-53/rules/dms/index.ts
> +export { default as nist80053DMSReplicationNotPublic } from './nist800053DMSReplicationNotPublic'
```suggestion
/*
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
export { default as nist80053DMSReplicationNotPublic } from './nist800053DMSReplicationNotPublic' 
```

2021-08-04 21:34 UTC, dontirun commented on src/NIST-800-53/rules/dms/nist800053DMSReplicationNotPublic.ts
> +    if (publicAccess) {
According to [Cfn Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html#cfn-dms-replicationinstance-publiclyaccessible) if this value is `undefined` then public access in enabled by default
```suggestion
    if (!(publicAccess === false) ) {
```

2021-08-04 21:34 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +    test('nist80053DMSReplication: - DMS replication is not public - (Control ID: AC-4)', () => {
```suggestion
    test('nist80053DMSReplication: DMS replication instances are not public - (Control ID: AC-4)', () => {
```

2021-08-04 21:34 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +      const messages2 = SynthUtils.synthesize(positive).messages;
```suggestion
      const messages2 = SynthUtils.synthesize(negative).messages;
```

2021-08-04 21:34 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +        publiclyAccessible: true,
```suggestion
```

2021-08-04 21:34 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +      expect(messages2).toContainEqual(
```suggestion
      expect(messages2).not.toContainEqual(
```

2021-08-04 21:35 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +      new CfnReplicationInstance(positive, 'rInstance', {
```suggestion
      new CfnReplicationInstance(negative, 'rInstance', {
```

2021-08-05 14:15 UTC, jen-rich commented
resolves #34

2021-08-05 14:27 UTC, dontirun requested changes

2021-08-05 14:27 UTC, dontirun commented on src/NIST-800-53/nist-800-53.ts
> +      const info = 'The DMS replication is public (Control IDs: AC-3).';
```suggestion
      const info = 'The DMS replication instance is public (Control IDs: AC-3).';
```

2021-08-05 14:27 UTC, dontirun commented on src/NIST-800-53/rules/dms/index.ts
> +export { default as nist80053DMSReplicationNotPublic } from './nist800053DMSReplicationNotPublic';
```suggestion
/*
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
export { default as nist80053DMSReplicationNotPublic } from './nist800053DMSReplicationNotPublic';
```

2021-08-05 14:27 UTC, dontirun commented on test/NIST-800-53/NIST-800-53-DMS.test.ts
> +  test('nist80053DMSReplication: - DMS replication is not public - (Control ID: AC-4)', () => {
```suggestion
  test('nist80053DMSReplication: DMS replication instances are not public - (Control ID: AC-4)', () => {
```

2021-08-05 17:45 UTC, dontirun requested changes
Fixes in some of the documentation changes

2021-08-05 17:56 UTC, dontirun requested changes
Fixes in some of the documentation changes

2021-08-05 20:31 UTC, dontirun approved these changes

2021-08-05 20:38 UTC, merged