fix: check unencrypted volumes from launch template, launch configuration and instance
cdklabs/cdk-nag pull request #1297
Opened 2023-05-12 13:28 UTC by clueleaf

Fixes #1167

2023-05-12 14:44 UTC, dontirun requested changes
The[ rule `info`](https://github.com/cdklabs/cdk-nag/blob/14b7ad608e588ed66230500fb0fd822a30090ef8/src/packs/aws-solutions.ts#L260) should be updated to be a bit more helpful.

I think something like `The resource creates one or more EBS volumes that have encryption disabled.`

The EBS volume has encryption disabled

2023-05-12 14:44 UTC, dontirun commented on test/rules/EC2.test.ts
> +      new CfnVolume(stack, 'rVolume', {
Let's remove the `r` from the Ids ( ex. `rVolume` -> `Volume`). It's from a naming convention used for regular CloudFormation that I initially carried over to here but am removing as new PRs are made.

2023-05-12 14:44 UTC, dontirun commented on src/rules/ec2/EC2EBSVolumeEncrypted.ts
> +          if (encryption != true) {
```suggestion
          if (encryption !== true) {
```

2023-05-12 14:44 UTC, dontirun commented on src/rules/ec2/EC2EBSVolumeEncrypted.ts
> +          if (encryption != true) {
```suggestion
          if (encryption !== true) {
```

2023-05-12 14:44 UTC, dontirun commented on src/rules/ec2/EC2EBSVolumeEncrypted.ts
> +          if (encryption != true) {
```suggestion
          if (encryption !== true) {
```

2023-05-12 14:44 UTC, dontirun commented on src/rules/ec2/EC2EBSVolumeEncrypted.ts
> +          if (encryption != true) {
```suggestion
          if (encryption !== true) {
```

2023-05-13 00:13 UTC, clueleaf commented
@dontirun 
Thank you for your review. I think your comments are all resolved now.

2023-05-13 02:58 UTC, dontirun approved these changes
Thanks for the contribution!

2023-05-13 03:06 UTC, merged