feat(nag-logger): provide loggers with rule name
cdklabs/cdk-nag pull request #1550
Opened 2024-01-04 02:43 UTC by cogwirrel

For use cases where we want to build further automation around CDK Nag, it's useful to be able to identify the original CDK Nag rule which was applied. This change provides loggers with the original rule name.

The practical use case I'm looking at is automating the generation of base [Threat Composer](https://github.com/awslabs/threat-composer) threat models. The idea is that based on CDK Nag's introspection of your infrastructure, we can map CDK Nag rules to particular threats that they would mitigate, and so provide a good starting point from which to build a threat model for an application.

With the rule name available in a logger, I only need to worry about mapping CDK Nag rule names to threats, rather than maintaining mappings for each nag pack's rule ID, or only supporting a specific nag pack :)

2024-01-04 21:18 UTC, dontirun commented on src/nag-logger.ts
> +  readonly ruleName: string;
Lets change this to `ruleOriginalName`

2024-01-04 21:20 UTC, dontirun requested changes
Looks good overall! Requesting some minor changes

2024-01-04 21:20 UTC, dontirun commented on src/nag-logger.ts
>   * @param ruleId Why the rule was triggered.
I know this isn't a change you made, but let's fix this in this PR 😄 

```suggestion
 * @param ruleId The id of the rule to ignore.
```

2024-01-04 21:20 UTC, dontirun commented on src/nag-logger.ts
>   * @param ruleInfo The id of the rule to ignore.
I know this isn't a change you made, but let's fix this in this PR 😄

```suggestion
 * @param ruleInfo Why the rule was triggered.
```

2024-01-04 22:09 UTC, cogwirrel commented
> Looks good overall! Requesting some minor changes

Thanks for the review! :)

2024-01-05 14:06 UTC, dontirun approved these changes

2024-01-05 14:10 UTC, merged

2024-01-05 15:34 UTC, dontirun commented
Thanks for the contribution @cogwirrel 😄