feat: lambda logging rules
cdklabs/cdk-nag pull request #1677
Opened 2024-04-29 04:28 UTC by Kevinwochan

[Serverless Nag Pack - lambda logging rules](https://github.com/cdklabs/cdk-nag/issues/1676)

First rule of many to check if this is in-line with the team's standards

2024-05-06 19:14 UTC, dontirun requested changes
Please add this to the [Additional Rules section](https://github.com/cdklabs/cdk-nag/blob/main/RULES.md#additional-rules) in the `RULES.md`file.

That section lists rules that are not currently part of any  included `NagPacks`

2024-05-06 19:14 UTC, dontirun commented on test/rules/Lambda.test.ts
> +      new CfnFunction(stack, 'rFunction', {
```suggestion
      new CfnFunction(stack, 'Function', {
```

The `r` is a CloudFormation naming convention which shouldn't be used in CDK. I mistakenly followed this pattern in some of the older tests.

2024-05-06 19:14 UTC, dontirun commented on test/rules/Lambda.test.ts
> +  describe('LambdaLogging: Ensure that Lambda functions have a corresponding Log Group', () => {
General comment, also add some tests using the `L2` construct (if possible). There are some cases ([example](https://github.com/cdklabs/cdk-nag/blob/main/src/rules/opensearch/OpenSearchNoUnsignedOrAnonymousAccess.ts#L42)) where the CDK uses custom resources/alternative patterns to achieve the same functionality. Having tests that use L2 constructs help us catch some of these problems

2024-05-06 19:14 UTC, dontirun commented on src/rules/lambda/LambdaLogging.ts
> + * Ensure that Lambda functions have a corresponding Log Group
```suggestion
 * Lambda functions explicitly define their CloudWatch Log Groups
```

 Rule comments are declarative

2024-05-22 15:54 UTC, dontirun requested changes
- All the rules that are being added need tests.
- The Serverless Pack needs its own section in the RULES file
- The Serverless Pack needs a test
- Rule info needs to be declarative 
-  Explanations needs to describe the benefit of doing what the rule tells you to do

2024-06-17 04:43 UTC, Kevinwochan commented
I've written up rules for the rest of the pack.
Just thought i'd get this Lambda Log rule through first so i can make sure the rest of the serverless pack implementation aligns

2024-06-17 04:43 UTC, Kevinwochan commented on src/rules/appsync/AppSyncTracing.ts
> + * Ensure that AppSync APIs have tracing enabled
removed from this PR

2024-06-17 04:43 UTC, Kevinwochan commented on src/packs/serverless.ts
> +        'Amazon API Gateway provides active tracing support for AWS X-Ray. Enable active tracing on your API stages to sample incoming requests and send traces to X-Ray.',
Removed from this PR

2024-06-17 04:44 UTC, Kevinwochan commented on RULES.md
> +| LambdaLogging | The Lambda Function does not define a corresponding log group | Ensure that Lambda functions have a corresponding Log Group |
Updated with the value of explicit logging

2024-06-24 19:27 UTC, dontirun requested changes

2024-06-24 19:27 UTC, dontirun commented on RULES.md
> +| LambdaLogLevel | The Lambda Function does not define an explicit Log Level | For cost optimization purposes, you should explicitly define the required log level for cost effective storage of Lambda
This is for the wrong rule

2024-06-24 19:27 UTC, dontirun commented on test/rules/Lambda.test.ts
> +  describe('LambdaLogLevel: Lambda functions have a explicit log level', () => {
It looks like these tests are for the wrong rule

2024-07-15 23:54 UTC, closed without merging