fix: AwsSolutions-APIG4 triggers for CORS preflight endpoints
cdklabs/cdk-nag pull request #1816
Opened 2024-10-22 13:34 UTC by georeeve

Fixes #1815.

Currently this PR just marks all `OPTIONS` methods as compliant. I'm not sure the best way to narrow this down to specifically CORS preflight endpoints. We could try and match the template that CDK generates through its `addCorsPreflight` method, but that won't include any custom preflight endpoints which people may be using, and any changes to the CDK template may break our checks here.

I took a look at the [MDN docs for the `OPTIONS` method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS), and it seems like it has limited use cases outside of CORS. Perhaps we can mark them all as compliant?

Here is the CloudFormation CfnMethod template which CDK generates when using the following code:
```typescript
new apigateway.RestApi(this, 'TestRestApi', {
    restApiName: 'Test',
    defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
    },
});
```

```json
{
  "apiKeyRequired": false,
  "authorizationType": "NONE",
  "httpMethod": "OPTIONS",
  "integration": {
    "type": "MOCK",
    "requestTemplates": {
      "application/json": "{ statusCode: 200 }"
    },
    "integrationResponses": [
      {
        "statusCode": "204",
        "responseParameters": {
          "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
          "method.response.header.Access-Control-Allow-Origin": "'*'",
          "method.response.header.Access-Control-Allow-Methods": "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
        }
      }
    ]
  },
  "methodResponses": [
    {
      "statusCode": "204",
      "responseParameters": {
        "method.response.header.Access-Control-Allow-Headers": true,
        "method.response.header.Access-Control-Allow-Origin": true,
        "method.response.header.Access-Control-Allow-Methods": true
      }
    }
  ],
  "resourceId": {
    "Fn::GetAtt": ["Test", "RootResourceId"]
  },
  "restApiId": {
    "Ref": "Test"
  }
}
```

2024-10-22 15:30 UTC, dontirun commented
I thinks it's better to keep the current implementation of the rule and add additional information on the description that it may not apply to pre-flight endpoints Instead of marking all `OPTIONS`as compliant.

While not ideal I'd rather users suppress false positives instead of opening up the rule for false negatives

2024-10-22 15:35 UTC, georeeve commented
If we are concerned about false negatives, then we could at least take the other approach of matching the built-in CORS feature by matching against the `MOCK` integration outlined above. Again, we might have to change if it CDK changes their implementation, but I think it's better than simply updating the rule description and having users craft their own exemption config for what is a built-in feature to CDK.

2024-10-22 15:41 UTC, georeeve commented
Perhaps we could be a bit more generic and check the above `methodResponses`? I don't imagine they're likely to change, and I can't see why you would return that on any other `OPTIONS` endpoint which is not dedicated to responding to CORS preflight requests.

2024-10-22 16:55 UTC, georeeve commented
I've just updated the check to match the `methodResponses` responses above. I think this is a better approach than just updating the description, but please have a look and let me know.

2024-10-24 16:10 UTC, dontirun commented
> However, I did try and come up with an exemption config which only exempts `OPTIONS` methods, but I couldn't get it to work for some reason. Do you have any examples that I could use if so?

You can mark that specific case as [NagRuleCompliance.NOT_APPLICABLE](https://github.com/cdklabs/cdk-nag/blob/c40f7255a9ff6dab71d14e4188047065036b903e/docs/RuleCreation.md#anatomy-of-a-rule)

2024-10-24 16:11 UTC, dontirun requested changes

2024-10-24 16:11 UTC, dontirun commented on src/rules/apigw/APIGWAuthorization.ts
> +          return NagRuleCompliance.COMPLIANT;
Given the spec I think it's safe to change this from `COMPLIANT` to `NOT_APPLICABLE`

2024-10-24 18:21 UTC, georeeve commented on test/rules/APIGW.test.ts
> +      new RestApi(stack, 'rRestApi').root.addMethod('OPTIONS');
Done, I've just removed it from the tests within the describe block, let me know if you want it removed for the whole file.

2024-10-24 18:59 UTC, dontirun approved these changes

2024-10-24 19:03 UTC, merged