Throws error when addResourceSuppressionsByPath does not match any resources.
cdklabs/cdk-nag pull request #799
Opened 2022-04-22 19:27 UTC by maclema

When calling addResourceSuppressionsByPath, if no resource is found an error is thrown. Calling addResourceSuppressionsByPath and not finding a resource could indicate a problem in the code, and could lead to future unintended suppressions.

2022-04-26 15:48 UTC, dontirun requested changes

2022-05-03 01:05 UTC, dontirun requested changes

2022-05-03 01:05 UTC, dontirun commented on test/Engine.test.ts
> +        'Error: Suppression path did not match any resource'
Needs to be updated with new Error message

2022-05-05 23:35 UTC, maclema commented
Confirmed unit tests passing with updated error message.

2022-05-06 15:55 UTC, dontirun approved these changes

2022-05-06 15:55 UTC, merged

2022-05-06 16:34 UTC, dontirun commented
Related to #800

2022-05-06 16:43 UTC, dontirun commented
@maclema Thanks for the contribution!